  CREATE TABLE "SCOTT"."CUSTOMER" 
   (	"USERNAME" VARCHAR2(30 BYTE) NOT NULL ENABLE, 
	"FNAME" VARCHAR2(25 BYTE), 
	"LNAME" VARCHAR2(25 BYTE), 
	"LOCATION" VARCHAR2(200 BYTE), 
	"CREDIT_NO" VARCHAR2(100 BYTE), 
	"PASSWORD" VARCHAR2(100 BYTE) NOT NULL ENABLE, 
	 CONSTRAINT "CUSTOMER_PK" PRIMARY KEY ("USERNAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
 

  

  CREATE TABLE "SCOTT"."DELIVERY_PARTNER" 
   (	"USERNAME" VARCHAR2(30 BYTE) NOT NULL ENABLE, 
	"VEHICLE" VARCHAR2(50 BYTE), 
	"PASSWORD" VARCHAR2(100 BYTE) NOT NULL ENABLE, 
	"RATING" FLOAT(126) DEFAULT 0 NOT NULL ENABLE, 
	 CONSTRAINT "DELIVERY_PARTNER_PK" PRIMARY KEY ("USERNAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
 


 
 
  
  CREATE TABLE "SCOTT"."RESTAURANT" 
   (	"RESTAURANT_NAME" VARCHAR2(30 BYTE) NOT NULL ENABLE, 
	"RESTAURANT_LOCATION" VARCHAR2(200 BYTE) NOT NULL ENABLE, 
	"RATING" NUMBER DEFAULT 1 NOT NULL ENABLE, 
	"CUISINE_TYPE" VARCHAR2(50 BYTE), 
	"RESTAURANT_IMAGE" VARCHAR2(200 BYTE), 
	 CONSTRAINT "RESTAURANT_PK" PRIMARY KEY ("RESTAURANT_NAME", "RESTAURANT_LOCATION")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;


  CREATE TABLE "SCOTT"."FOOD" 
   (	"FOOD_NAME" VARCHAR2(50 BYTE) NOT NULL ENABLE, 
	"RESTAURANT_NAME" VARCHAR2(30 BYTE) NOT NULL ENABLE, 
	"RESTAURANT_LOCATION" VARCHAR2(200 BYTE) NOT NULL ENABLE, 
	"PRICE" FLOAT(126) DEFAULT 0 NOT NULL ENABLE, 
	"DISCOUNT" NUMBER DEFAULT 0 NOT NULL ENABLE, 
	"RATING" NUMBER DEFAULT 1 NOT NULL ENABLE, 
	"INGREDIANTS" VARCHAR2(500 BYTE), 
	"TOP_DISH" VARCHAR2(3 BYTE) DEFAULT 'n' NOT NULL ENABLE, 
	"FOODIMAGE" VARCHAR2(300 BYTE), 
	"FOODTYPE" VARCHAR2(30 BYTE), 
	 CONSTRAINT "FOOD_PK" PRIMARY KEY ("FOOD_NAME", "RESTAURANT_NAME", "RESTAURANT_LOCATION")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE, 
	 CONSTRAINT "FOOD_RESTAURANT_FK1" FOREIGN KEY ("RESTAURANT_NAME", "RESTAURANT_LOCATION")
	  REFERENCES "SCOTT"."RESTAURANT" ("RESTAURANT_NAME", "RESTAURANT_LOCATION") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
 

 
 
  CREATE TABLE "SCOTT"."ORDERS" 
   (	"ORDER_ID" NUMBER(*,0) NOT NULL ENABLE, 
	"TIP" NUMBER DEFAULT 0 NOT NULL ENABLE, 
	"ORDER_DATE" DATE DEFAULT sysdate NOT NULL ENABLE, 
	"PAYMENT_TYPE" VARCHAR2(20 BYTE) DEFAULT 'cash' NOT NULL ENABLE, 
	"STATUS" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"CUSTOMER_USERNAME" VARCHAR2(20 BYTE), 
	"FOOD_PRICE" FLOAT(126) DEFAULT 0 NOT NULL ENABLE, 
	 CONSTRAINT "ORDERR_PK" PRIMARY KEY ("ORDER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE, 
	 CONSTRAINT "ORDERS_CUSTOMER_FK1" FOREIGN KEY ("CUSTOMER_USERNAME")
	  REFERENCES "SCOTT"."CUSTOMER" ("USERNAME") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
 











 
  CREATE TABLE "SCOTT"."ORDER_FOOD" 
   (	"ORDER_ID" NUMBER(*,0) NOT NULL ENABLE, 
	"RESTAURANT_NAME" VARCHAR2(30 BYTE) NOT NULL ENABLE, 
	"RESTAURANT_LOCATION" VARCHAR2(200 BYTE) NOT NULL ENABLE, 
	"FOOD_NAME" VARCHAR2(50 BYTE) NOT NULL ENABLE, 
	"NO_OF_ITEMS_PER_FOOD" NUMBER DEFAULT 1 NOT NULL ENABLE, 
	"BOUGHT" VARCHAR2(2 BYTE) DEFAULT 'n' NOT NULL ENABLE, 
	 CONSTRAINT "ORDER_FOOD_PK" PRIMARY KEY ("ORDER_ID", "RESTAURANT_NAME", "RESTAURANT_LOCATION", "FOOD_NAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE, 
	 CONSTRAINT "ORDER_FOOD_ORDER_FK1" FOREIGN KEY ("ORDER_ID")
	  REFERENCES "SCOTT"."ORDERS" ("ORDER_ID") ENABLE, 
	 CONSTRAINT "ORDER_FOOD_FOOD_FK1" FOREIGN KEY ("FOOD_NAME", "RESTAURANT_NAME", "RESTAURANT_LOCATION")
	  REFERENCES "SCOTT"."FOOD" ("FOOD_NAME", "RESTAURANT_NAME", "RESTAURANT_LOCATION") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
 


  CREATE TABLE "SCOTT"."REST_NUMBERS" 
   (	"RESTAURANT_NAME" VARCHAR2(30 BYTE) NOT NULL ENABLE, 
	"RESTAURANT_LOCATION" VARCHAR2(200 BYTE) NOT NULL ENABLE, 
	"PHONE_NO" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	 CONSTRAINT "REST_NUMBERS_PK" PRIMARY KEY ("RESTAURANT_NAME", "RESTAURANT_LOCATION", "PHONE_NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "USERS"  ENABLE, 
	 CONSTRAINT "REST_NUMBERS_RESTAURANT_FK1" FOREIGN KEY ("RESTAURANT_NAME", "RESTAURANT_LOCATION")
	  REFERENCES "SCOTT"."RESTAURANT" ("RESTAURANT_NAME", "RESTAURANT_LOCATION") ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
 

  CREATE TABLE "SCOTT"."TRIP" 
   (	"ORDER_ID" NUMBER(*,0) DEFAULT 0 NOT NULL ENABLE, 
	"DISTANCE_OF_TRIP" FLOAT(126) DEFAULT 0 NOT NULL ENABLE, 
	"DELIVERYPARTNER_USERNAME" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"DELIVERYFEES" FLOAT(126) DEFAULT 0 NOT NULL ENABLE, 
	 CONSTRAINT "TRIP_PK" PRIMARY KEY ("ORDER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE, 
	 CONSTRAINT "TRIP_DELIVERY_PARTNER_FK1" FOREIGN KEY ("DELIVERYPARTNER_USERNAME")
	  REFERENCES "SCOTT"."DELIVERY_PARTNER" ("USERNAME") ENABLE, 
	 CONSTRAINT "ORDER_TRIP_FK1" FOREIGN KEY ("ORDER_ID")
	  REFERENCES "SCOTT"."ORDERS" ("ORDER_ID") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

 


  CREATE TABLE "SCOTT"."WORKING_TIME" 
   (	"DAY" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"RESTAURANT_NAME" VARCHAR2(30 BYTE) NOT NULL ENABLE, 
	"RESTAURANT_LOCATION" VARCHAR2(200 BYTE) NOT NULL ENABLE, 
	"START_TIME" NUMBER, 
	"END_TIME" NUMBER, 
	 CONSTRAINT "WORKING_TIME_PK" PRIMARY KEY ("DAY", "RESTAURANT_NAME", "RESTAURANT_LOCATION")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "USERS"  ENABLE, 
	 CONSTRAINT "WORKING_TIME_RESTAURANT_FK1" FOREIGN KEY ("RESTAURANT_NAME", "RESTAURANT_LOCATION")
	  REFERENCES "SCOTT"."RESTAURANT" ("RESTAURANT_NAME", "RESTAURANT_LOCATION") ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
 
