//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class CUSTOMER
{
    public string USERNAME { get; set; }
    public string FNAME { get; set; }
    public string LNAME { get; set; }
    public string LOCATION { get; set; }
    public string CREDIT_NO { get; set; }
    public string PASSWORD { get; set; }
}
