//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Uber_Eats_Database_Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class CUSTOMER
    {
        public CUSTOMER()
        {
            this.ORDERS = new HashSet<ORDER>();
        }
    
        public string USERNAME { get; set; }
        public string FNAME { get; set; }
        public string LNAME { get; set; }
        public string LOCATION { get; set; }
        public string CREDIT_NO { get; set; }
        public string PASSWORD { get; set; }
    
        public virtual ICollection<ORDER> ORDERS { get; set; }
    }
}
