//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class DELIVERY_PARTNER
{
    public DELIVERY_PARTNER()
    {
        this.TRIPs = new HashSet<TRIP>();
    }

    public string USERNAME { get; set; }
    public Nullable<decimal> NO_OF_TRIPS { get; set; }
    public string VEHICLE { get; set; }
    public string PASSWORD { get; set; }
    public Nullable<decimal> RATING { get; set; }

    public virtual ICollection<TRIP> TRIPs { get; set; }
}
