//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Uber_Eats_Database_Project
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<CUSTOMER> CUSTOMERs { get; set; }
        public DbSet<FOOD> FOODs { get; set; }
        public DbSet<ORDER_FOOD> ORDER_FOOD { get; set; }
        public DbSet<ORDER> ORDERS { get; set; }
        public DbSet<REST_NUMBERS> REST_NUMBERS { get; set; }
        public DbSet<RESTAURANT> RESTAURANTs { get; set; }
        public DbSet<TRIP> TRIPs { get; set; }
        public DbSet<WORKING_TIME> WORKING_TIME { get; set; }
        public DbSet<DELIVERY_PARTNER> DELIVERY_PARTNER { get; set; }
    
        public virtual int SIGN_UP(string nUSERNAME, string nPASSWORD, Nullable<decimal> nROLE, ObjectParameter dONE, string nFNAME, string nLNAME, string nLOCATION, string nCREDIT_NO, string nVEHICLE)
        {
            var nUSERNAMEParameter = nUSERNAME != null ?
                new ObjectParameter("NUSERNAME", nUSERNAME) :
                new ObjectParameter("NUSERNAME", typeof(string));
    
            var nPASSWORDParameter = nPASSWORD != null ?
                new ObjectParameter("NPASSWORD", nPASSWORD) :
                new ObjectParameter("NPASSWORD", typeof(string));
    
            var nROLEParameter = nROLE.HasValue ?
                new ObjectParameter("NROLE", nROLE) :
                new ObjectParameter("NROLE", typeof(decimal));
    
            var nFNAMEParameter = nFNAME != null ?
                new ObjectParameter("NFNAME", nFNAME) :
                new ObjectParameter("NFNAME", typeof(string));
    
            var nLNAMEParameter = nLNAME != null ?
                new ObjectParameter("NLNAME", nLNAME) :
                new ObjectParameter("NLNAME", typeof(string));
    
            var nLOCATIONParameter = nLOCATION != null ?
                new ObjectParameter("NLOCATION", nLOCATION) :
                new ObjectParameter("NLOCATION", typeof(string));
    
            var nCREDIT_NOParameter = nCREDIT_NO != null ?
                new ObjectParameter("NCREDIT_NO", nCREDIT_NO) :
                new ObjectParameter("NCREDIT_NO", typeof(string));
    
            var nVEHICLEParameter = nVEHICLE != null ?
                new ObjectParameter("NVEHICLE", nVEHICLE) :
                new ObjectParameter("NVEHICLE", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SIGN_UP", nUSERNAMEParameter, nPASSWORDParameter, nROLEParameter, dONE, nFNAMEParameter, nLNAMEParameter, nLOCATIONParameter, nCREDIT_NOParameter, nVEHICLEParameter);
        }
    
        public virtual int COUNT_GETCARTITEMS(Nullable<decimal> cURRENT_ORDER_ID, ObjectParameter cNT)
        {
            var cURRENT_ORDER_IDParameter = cURRENT_ORDER_ID.HasValue ?
                new ObjectParameter("CURRENT_ORDER_ID", cURRENT_ORDER_ID) :
                new ObjectParameter("CURRENT_ORDER_ID", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("COUNT_GETCARTITEMS", cURRENT_ORDER_IDParameter, cNT);
        }
    
        public virtual int CREATE_CART(string cUSERNAME)
        {
            var cUSERNAMEParameter = cUSERNAME != null ?
                new ObjectParameter("CUSERNAME", cUSERNAME) :
                new ObjectParameter("CUSERNAME", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CREATE_CART", cUSERNAMEParameter);
        }
    
        public virtual int DELETE_CART_ITEM(Nullable<decimal> oRDERID, string rEST_NAME, string rEST_LOC, string fOOD_NAME)
        {
            var oRDERIDParameter = oRDERID.HasValue ?
                new ObjectParameter("ORDERID", oRDERID) :
                new ObjectParameter("ORDERID", typeof(decimal));
    
            var rEST_NAMEParameter = rEST_NAME != null ?
                new ObjectParameter("REST_NAME", rEST_NAME) :
                new ObjectParameter("REST_NAME", typeof(string));
    
            var rEST_LOCParameter = rEST_LOC != null ?
                new ObjectParameter("REST_LOC", rEST_LOC) :
                new ObjectParameter("REST_LOC", typeof(string));
    
            var fOOD_NAMEParameter = fOOD_NAME != null ?
                new ObjectParameter("FOOD_NAME", fOOD_NAME) :
                new ObjectParameter("FOOD_NAME", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DELETE_CART_ITEM", oRDERIDParameter, rEST_NAMEParameter, rEST_LOCParameter, fOOD_NAMEParameter);
        }
    
        public virtual int GETALLORDERS(string uSER_NAME)
        {
            var uSER_NAMEParameter = uSER_NAME != null ?
                new ObjectParameter("USER_NAME", uSER_NAME) :
                new ObjectParameter("USER_NAME", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GETALLORDERS", uSER_NAMEParameter);
        }
    
        public virtual int GETCARTID(string cURRENT_USER_NAME, ObjectParameter c_ID)
        {
            var cURRENT_USER_NAMEParameter = cURRENT_USER_NAME != null ?
                new ObjectParameter("CURRENT_USER_NAME", cURRENT_USER_NAME) :
                new ObjectParameter("CURRENT_USER_NAME", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GETCARTID", cURRENT_USER_NAMEParameter, c_ID);
        }
    
        public virtual int GETCARTITEMS(Nullable<decimal> cURRENT_ORDER_ID)
        {
            var cURRENT_ORDER_IDParameter = cURRENT_ORDER_ID.HasValue ?
                new ObjectParameter("CURRENT_ORDER_ID", cURRENT_ORDER_ID) :
                new ObjectParameter("CURRENT_ORDER_ID", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GETCARTITEMS", cURRENT_ORDER_IDParameter);
        }
    
        public virtual int UPDATE_CART_ITEMS(Nullable<decimal> oRDERID, string rEST_NAME, string rEST_LOC, string fOOD_NAME, Nullable<decimal> nO_OF_ITEMS)
        {
            var oRDERIDParameter = oRDERID.HasValue ?
                new ObjectParameter("ORDERID", oRDERID) :
                new ObjectParameter("ORDERID", typeof(decimal));
    
            var rEST_NAMEParameter = rEST_NAME != null ?
                new ObjectParameter("REST_NAME", rEST_NAME) :
                new ObjectParameter("REST_NAME", typeof(string));
    
            var rEST_LOCParameter = rEST_LOC != null ?
                new ObjectParameter("REST_LOC", rEST_LOC) :
                new ObjectParameter("REST_LOC", typeof(string));
    
            var fOOD_NAMEParameter = fOOD_NAME != null ?
                new ObjectParameter("FOOD_NAME", fOOD_NAME) :
                new ObjectParameter("FOOD_NAME", typeof(string));
    
            var nO_OF_ITEMSParameter = nO_OF_ITEMS.HasValue ?
                new ObjectParameter("NO_OF_ITEMS", nO_OF_ITEMS) :
                new ObjectParameter("NO_OF_ITEMS", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UPDATE_CART_ITEMS", oRDERIDParameter, rEST_NAMEParameter, rEST_LOCParameter, fOOD_NAMEParameter, nO_OF_ITEMSParameter);
        }
    
        public virtual int UPDATE_ORDER_STATUS_NC_TO_PD(Nullable<decimal> oRDERID)
        {
            var oRDERIDParameter = oRDERID.HasValue ?
                new ObjectParameter("ORDERID", oRDERID) :
                new ObjectParameter("ORDERID", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UPDATE_ORDER_STATUS_NC_TO_PD", oRDERIDParameter);
        }
    }
}
