//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;

public partial class Entities : DbContext
{
    public Entities()
        : base("name=Entities")
    {
    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }

    public DbSet<CUSTOMER> CUSTOMERs { get; set; }
    public DbSet<DELIVERY_PARTNER> DELIVERY_PARTNER { get; set; }
    public DbSet<FOOD> FOODs { get; set; }
    public DbSet<FOOD_TYPE> FOOD_TYPE { get; set; }
    public DbSet<ORDER_FOOD> ORDER_FOOD { get; set; }
    public DbSet<ORDER> ORDERS { get; set; }
    public DbSet<REST_NUMBERS> REST_NUMBERS { get; set; }
    public DbSet<RESTAURANT> RESTAURANTs { get; set; }
    public DbSet<TRIP> TRIPs { get; set; }
    public DbSet<WORKING_TIME> WORKING_TIME { get; set; }

    public virtual int SIGN_UP(string nUSERNAME, string nPASSWORD, Nullable<decimal> nROLE, ObjectParameter dONE, string nFNAME, string nLNAME, string nLOCATION, string nCREDIT_NO, string nVEHICLE)
    {
        var nUSERNAMEParameter = nUSERNAME != null ?
            new ObjectParameter("NUSERNAME", nUSERNAME) :
            new ObjectParameter("NUSERNAME", typeof(string));

        var nPASSWORDParameter = nPASSWORD != null ?
            new ObjectParameter("NPASSWORD", nPASSWORD) :
            new ObjectParameter("NPASSWORD", typeof(string));

        var nROLEParameter = nROLE.HasValue ?
            new ObjectParameter("NROLE", nROLE) :
            new ObjectParameter("NROLE", typeof(decimal));

        var nFNAMEParameter = nFNAME != null ?
            new ObjectParameter("NFNAME", nFNAME) :
            new ObjectParameter("NFNAME", typeof(string));

        var nLNAMEParameter = nLNAME != null ?
            new ObjectParameter("NLNAME", nLNAME) :
            new ObjectParameter("NLNAME", typeof(string));

        var nLOCATIONParameter = nLOCATION != null ?
            new ObjectParameter("NLOCATION", nLOCATION) :
            new ObjectParameter("NLOCATION", typeof(string));

        var nCREDIT_NOParameter = nCREDIT_NO != null ?
            new ObjectParameter("NCREDIT_NO", nCREDIT_NO) :
            new ObjectParameter("NCREDIT_NO", typeof(string));

        var nVEHICLEParameter = nVEHICLE != null ?
            new ObjectParameter("NVEHICLE", nVEHICLE) :
            new ObjectParameter("NVEHICLE", typeof(string));

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SIGN_UP", nUSERNAMEParameter, nPASSWORDParameter, nROLEParameter, dONE, nFNAMEParameter, nLNAMEParameter, nLOCATIONParameter, nCREDIT_NOParameter, nVEHICLEParameter);
    }
}
